# Generated by Django 4.2.7 on 2023-11-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_approved_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
