# Generated by Django 4.2.7 on 2023-11-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_approved_post_post_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
