# Generated by Django 4.2.7 on 2023-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='username',
            field=models.SlugField(allow_unicode=True, default=18.39090909090909, unique=True),
            preserve_default=False,
        ),
    ]
