# Generated by Django 4.2.7 on 2023-11-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='username',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
