# Generated by Django 4.2.7 on 2023-11-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_username_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=12.26060606060606, unique=True),
            preserve_default=False,
        ),
    ]
