# Generated by Django 4.2.7 on 2023-11-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_created_date_group_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='published_date',
        ),
        migrations.AddField(
            model_name='group',
            name='approved_group',
            field=models.BooleanField(default=False),
        ),
    ]
